name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Instal deps
        run: |
          sudo apt install -y dnsutils libfile-which-perl libtest-tcp-perl

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: test
        run: make check

      - name: Snapshot GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot
